Remove FAQ page and add info page about demo instance
hedgedoc/hedgedoc.github.io pull request #149
Opened 2021-08-12 21:01 UTC by ErikMichelson

### Description
This PR removes the FAQ page as that will be moved to the docs.
To answer the questions about the demo instance, there will be an extra page about the demo instance. This is intended to work as an interstitial page showing users why they should not rely on the demo instance.

### Steps
- [x] Added changes
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc.github.io/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### Related Issue(s)
following

2021-08-14 10:19 UTC, mrdrogdrog commented
Why should we move the FAQ to the docs?

2021-08-14 13:06 UTC, ErikMichelson commented
We discussed that the contents of the FAQ are more docs-relevant. And we wanted to avoid having things in two places.

2021-08-14 13:10 UTC, mrdrogdrog commented
When and where

2021-08-14 20:57 UTC, davidmehren commented
@mrdrogdrog https://github.com/hedgedoc/hedgedoc/pull/1532 adds more technical questions to the FAQ.
Also, the FAQs on the homepage can't be searched by the docs search. Therefore, moving the FAQ to the docs improves the user experience.

2021-08-20 06:43 UTC, DerMolly requested changes

2021-08-20 06:43 UTC, DerMolly commented on content/english/demo.md
> +Some countries have a too high latency to the demo instance, which means HedgeDoc would be unusable. To make the demo available in as many countries as possible, we use [Cloudflare](https://www.cloud
I think this sentence needs some rearrangement. Maybe start with `To make the demo available…`

2021-08-29 06:40 UTC, mrdrogdrog commented
Don't forget to add the faq page AND the draft faq entries to the develop branch!

2021-08-29 06:41 UTC, mrdrogdrog approved these changes

2021-08-29 06:52 UTC, DerMolly approved these changes

2021-08-29 16:16 UTC, davidmehren approved these changes

2021-08-29 16:21 UTC, merged