feat: add history.md file from the docs
hedgedoc/hedgedoc.github.io pull request #269
Opened 2022-06-07 18:53 UTC by DerMolly

### Description
This PR adds the history.md file from the history.

### Steps

- [x] Added changes
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc.github.io/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### Related Issue(s)
https://github.com/hedgedoc/hedgedoc/issues/2338

2022-06-07 19:05 UTC, mrdrogdrog commented
Why?

2022-06-07 23:05 UTC, DerMolly commented
> Why?

See https://github.com/hedgedoc/hedgedoc/issues/2338

2022-06-12 18:27 UTC, davidmehren requested changes

2022-06-12 18:27 UTC, davidmehren commented on content/english/history/details/index.md
> +If you want to look at a more visual explanation, you can find this [here](/history).
```suggestion
If you don't like text, there is also a [visual explanation](/history).
```

2022-06-12 18:32 UTC, mrdrogdrog approved these changes

2022-06-12 18:56 UTC, davidmehren approved these changes

2022-06-12 18:59 UTC, merged